### ISSUE TITLE
Scaling containers

### ISSUE THREAD

**Issue by jensskott** [akurkin/rancher-api#12]
Could you post a quick example how to scale containers with your gem?

**Comment by akurkin** [comment]
I assume you meant "scaling services", because container is just a single running unit and you can't scale it.

To scale services in rancher, it's enough to update service's `scale` property.

Via `rancher-api` you can do it like this:

```
service = Rancher::Api::Service.find('1s7938')
service.scale += 1
service.save!
```

What these instructions do:
1. loads service from rancher using id (of course you can use any other convenient way for you, i.e. searching by name for example)
2. changes `scale` attribute of the service resource to be +1
3. send request to rancher to add one more container to the specified service

**Comment by ozbillwang** [comment]
So can we make this gem not a sdk, but a real command line that I can run directly?

Currently I face issue (https://github.com/rancher/rancher/issues/8175) that both official `rancher-compose cli` and `rancher cli` don't work properly to implement the change in `rancher-compose.yml`

Seems the API call still works.

**Comment by akurkin** [comment]
Sure, I think binaries can be easily added to the gem, the question is why? because there are rancher-cli and rancher binaries available already that provide an API interface to rancher 🙂

**Comment by ozbillwang** [comment]
@akurkin 

Thanks 

As I explained early, currently I face issue (rancher/rancher#8175) that both official `rancher-compose`cli and `rancher cli` don't work properly to implement the change in rancher-compose.yml. So I think if this Ruby Gem can help me. 

I currently stuck with this issue that can't automation the Rancher deployment in CI/CD pipeline.

**Comment by akurkin** [comment]
@ozbillwang binaries aren't something that's available right now and I have neither plans nor intent to add them myself at the moment, feel free to send a pull request, I'm happy to merge 🙂
